### ISSUE TITLE
Duplicated CSS top property in the last challenge in Applied Visual Design

### ISSUE THREAD

**Issue by jromest** [freeCodeCamp/curriculum#205]
#### Description
I just found a duplicated CSS `top` property in Applied Visual Design: Make Motion More Natural Using a Bezier Curve, is this intended?

``` css
.balls {
    border-radius: 50%;
    top: 249px;
    position: fixed;  
    width: 50px;
    height: 50px;
    top: 60%;
    animation-name: jump;
    animation-duration: 2s;
    animation-iteration-count: infinite;
}
```
####  Link
https://learn.freecodecamp.org/responsive-web-design/applied-visual-design/make-motion-more-natural-using-a-bezier-curve
